name: Postman Newman execution

on:
  workflow_call:
    inputs:
      environment:
        description: Postman Environment
        type: string
        required: true
      commandAdditionalParameters:
        description: Postman Newman Command Additional Parameters
        type: string
      postmanCollectionId:
        description: Postman Collection Id
        type: string
        required: true
      postmanEnvironmentId:
        description: Postman Environment Id
        type: string
        required: false
        default: ${{ vars.POSTMAN_ENVIRONMENT_ID }}
      postmanTestingReportIterationCount:
        description: Postman Testing Report Iteration Count
        type: string
        required: true
      postmanTestingReportHideRequestBodies:
        description: Postman Testing Report Hide Request Bodies
        type: string
        required: true
      postmanTestingReportHideResponseBodies:
        description: Postman Testing Report Hide Response Bodies
        type: string
        required: true
      postmanTestingReportSkipEnvironmentVars:
        description: Postman Testing Report Skip Environment Variables
        type: string
        required: true
      postmanTestingReportSkipHeaders:
        description: Postman Testing Report Skip Headers
        type: string
        required: true
      postmanTestingReportFilename:
        description: Postman Testing Report Filename
        type: string
        required: true
      customerName:
        description: Customer Name
        type: string
        required: true

    secrets:
      GHCR_PAT:
        description: GHCR Personal Access Token
        required: true
      POSTMAN_API_KEY:
        description: Postman API Key
        required: true

jobs:
  run-postman-newman:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/eigenherd/docker-image-github-runner-postman:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}
    steps:
      - run: echo "Running 1 build with ${{ inputs.postmanCollectionId }}"
      - run: echo "Running 2 build with ${{ inputs.postmanEnvironmentId }}"
      - run: echo "Running 3 build with ${{ inputs.environment }}"
      - run: echo "Running 4 build with ${{ vars.POSTMAN_ENVIRONMENT_ID }}"