name: Postman Newman execution

on:
  workflow_call:
    inputs:
      environment:
        description: Postman Environment
        type: string
        required: true
      commandAdditionalParameters:
        description: Postman Newman Command Additional Parameters
        type: string
      postmanCollectionId:
        description: Postman Collection Id
        type: string
        required: true
      postmanEnvironmentId:
        description: Postman Environment Id
        type: string
        required: true
      postmanTestingReportIterationCount:
        description: Postman Testing Report Iteration Count
        type: string
        required: true
      postmanTestingReportHideRequestBodies:
        description: Postman Testing Report Hide Request Bodies
        type: string
        required: true
      postmanTestingReportHideResponseBodies:
        description: Postman Testing Report Hide Response Bodies
        type: string
        required: true
      postmanTestingReportSkipEnvironmentVars:
        description: Postman Testing Report Skip Environment Variables
        type: string
        required: true
      postmanTestingReportSkipHeaders:
        description: Postman Testing Report Skip Headers
        type: string
        required: true
      postmanTestingReportFilename:
        description: Postman Testing Report Filename
        type: string
        required: true
      customerName:
        description: Customer Name
        type: string
        required: true

    secrets:
      GHCR_PAT:
        description: GHCR Personal Access Token
        required: true
      POSTMAN_API_KEY:
        description: Postman API Key
        required: true

jobs:
  run-postman-newman:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    container:
      image: ghcr.io/eigenherd/docker-image-github-runner-postman:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}
    steps:
      - run: echo ${{ github.workspace }}
      - run: |
          mkdir -p ${{ github.workspace }}/output
          newman run "https://api.postman.com/collections/${{ inputs.postmanCollectionId }}?apikey=${{ secrets.POSTMAN_API_KEY }}" \
          -e "https://api.postman.com/environments/${{ inputs.postmanEnvironmentId }}?apikey=${{ secrets.POSTMAN_API_KEY }}" \
          -r htmlextra \
          --iteration-count ${{ inputs.postmanTestingReportIterationCount }} \
          --suppress-exit-code \
          --reporter-htmlextra-showFolderDescription \
          --reporter-htmlextra-showMarkdownLinks \
          --reporter-htmlextra-title "${{ inputs.customerName }} - ${{ github.repository }} - [#${{ github.run_number }}]" \
          --reporter-htmlextra-titleSize 6 \
          --reporter-htmlextra-browserTitle "${{ inputs.customerName }} - ${{ github.repository }} - [#${{ github.run_number }}]" \
          --reporter-htmlextra-hideRequestBody ${{ inputs.postmanTestingReportHideRequestBodies }} \
          --reporter-htmlextra-hideResponseBody ${{ inputs.postmanTestingReportHideResponseBodies }} \
          --reporter-htmlextra-skipEnvironmentVars ${{ inputs.postmanTestingReportSkipEnvironmentVars }} \
          --reporter-htmlextra-skipHeaders ${{ inputs.postmanTestingReportSkipHeaders }} \
          --reporter-htmlextra-export output/${{ inputs.postmanTestingReportFilename }} \
          ${{ inputs.commandAdditionalParameters }}
          find ${{ github.workspace }}/output
      - run: chmod 644 ${{ github.workspace }}/${{ inputs.postmanTestingReportFilename }}
      - run: echo "${PWD}"
      #- run: ls -lah /github/workspace
      - run: ls -lah ${PWD}
      - run: ls -lah 
      - run: ls -la /
      - run: ls -la /github
      - run: ls -la /__w
      - run: ls -la /__w/github-actions-jobs-postman-newman-sample
      - run: ls -la /__w/github-actions-jobs-postman-newman-sample/github-actions-jobs-postman-newman-sample
      - run: ls -la /__e
      - run: ls -la /__w/_temp
      - run: ls -la /__w/_actions
      - run: ls -la /__w/_actions/actions
      - run: ls -la /__w/_actions/actions/upload-artifact
      - run: ls -la /__t
      - run: ls -la /github/home
      - run: ls -la /github/workflow
      - run: find / -name hi.txt 2>/dev/null
      - name: Publish
        shell: bash
        run: |
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE" >> $GITHUB_ENV
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Postman Newman Testing Report
          path: ${{ github.workspace }}/${{ inputs.postmanTestingReportFilename }}